import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { getSession } from "@/lib/auth";
import ClientLayoutWrapper from "@/components/layout/ClientLayoutWrapper";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const outfit = Outfit({ subsets: ["latin"], variable: '--font-outfit' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SessionUser } from "@/types/user";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = (session?.user as SessionUser) || null;

  return (
    <html lang="en">
      <body className={`${inter.variable} ${outfit.variable}`}>
        <ClientLayoutWrapper user={user}>
          {children}
        </ClientLayoutWrapper>
      </body>
    </html>
  );
}
